; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
	miguel5612/MQUnifiedsensor@^3.0.0
	adafruit/Adafruit MPU6050@^2.2.6
	bodmer/TFT_eSPI@^2.5.43
	thexspaceacademy/XSpaceBioV10@^1.0.6
	jrowberg/I2Cdevlib-MPU6050@^1.0.0
	jeremycole/I2C Temperature Sensors derived from the LM75@^1.0.3
	adafruit/Adafruit GFX Library@^1.12.0
	adafruit/DHT sensor library@^1.4.6
